name: Build Lukko demo image

on:
  push:
  schedule:
    - cron: '15 3 * * *'  # every day at 03:15 (just wanted to avoid midnight)

jobs:
  build:
    name: Build Lukko demo image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@main
      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/edera-dev/lukko-demo:latest
